name: Run Test Classes

on:
  push:
    paths:
      - force-app/**
  workflow_dispatch:  # 👈 Adăugat pentru a permite rularea manuală

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:      
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Authenticate using SF_AUTH_UAT'
        run: | 
          echo ${{ secrets.SF_AUTH_UAT }} | sf org login sfdx-url -s -u

      - name: 'Validate' 
        run: |
          sf project deploy start -d force-app/ --test-level RunSpecifiedTests --tests "AccountTrigger_Test" -w 30
