name: Run Test Classes

on:
  push:
    paths:
      - force-app/**

jobs:
  run-test-classes-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install --global sfdx-cli
          sfdx --version
      - name: Login To Org
        run: |
          sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SF_AUTH_UAT }}")
      - name: Deploy to UAT Org
        run: |
          sfdx force:source:deploy -p force-app -u ${{ secrets.SF_AUTH_UAT }} -w 10
